import '../chat.dart';

class ChatsRepository {
  static List<Chat> loadChats() {
    List<Chat> allChats = <Chat>[
      Chat(
        id: 1,
        type: 0,
        idFrom: 12,
        image: 'assets/img/gabriel.jpeg',
        sticker: 'assets/img/gif/mimi9.gif',
        content: 'Heloo babie',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 2,
        type: 1,
        idFrom: 12,
        image: 'assets/img/lupita.png',
        sticker: 'assets/img/gif/mimi1.gif',
        content: 'We doing okay',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 2,
        type: 2,
        idFrom: 10,
        image: 'assets/img/irene.png',
        sticker: 'assets/img/gif/mimi2.gif',
        content: 'Ayeeeeeeeeeeee',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 3,
        type: 0,
        idFrom: 12,
        image: 'assets/img/irene.png',
        sticker: 'assets/img/gif/mimi3.gif',
        content: 'Ayeeeeeeeeeeee',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 4,
        type: 2,
        idFrom: 12,
        image: 'assets/img/irene.png',
        sticker: 'assets/img/gif/mimi4.gif',
        content: 'Ayeeeeeeeeeeee',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 5,
        type: 2,
        idFrom: 12,
        image: 'assets/img/irene.png',
        sticker: 'assets/img/gif/mimi5.gif',
        content: 'Ayeeeeeeeeeeee',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 6,
        type: 0,
        idFrom: 10,
        image: 'assets/img/irene.png',
        sticker: 'assets/img/gif/mimi6.gif',
        content: 'We good??',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 7,
        type: 1,
        idFrom: 10,
        image: 'assets/img/irene.png',
        sticker: 'assets/img/gif/mimi7.gif',
        content: 'Bosss',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 8,
        type: 0,
        idFrom: 10,
        image: 'assets/img/gabriel.jpeg',
        sticker: 'assets/img/gif/mimi9.gif',
        content: 'Am cool n u???',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
      Chat(
        id: 9,
        type: 0,
        idFrom: 10,
        image: 'assets/img/gabriel.jpeg',
        sticker: 'assets/img/gif/mimi9.gif',
        content: 'We good love',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
       Chat(
        id: 10,
        type: 1,
        idFrom: 12,
        image: 'assets/img/gabriel.jpeg',
        sticker: 'assets/img/gif/mimi9.gif',
        content: 'We good love',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
        Chat(
        id: 11,
        type: 0,
        idFrom: 12,
        image: 'assets/img/gabriel.jpeg',
        sticker: 'assets/img/gif/mimi9.gif',
        content: 'We good love',
        timestamp: DateTime.now().millisecondsSinceEpoch.toString(),
      ),
    ];
    return allChats.toList();
  }
}
